### PR TITLE
Release 3.2.0

### PR DESCRIPTION
**Pull request by repeatedly**
Will be merged after https://github.com/treasure-data/omnibus-td-agent/pull/165

### CODE REVIEW

**Comment by Techcadia** [comment]
I would love to see  a windows release as we have some bugs that are fixed in the current release of fluentd.

Specifically https://github.com/fluent/fluentd/pull/1874

Thanks

**Comment by repeatedly** [comment]
Yeah, we will work on td-agent 3.2.0 msi soon.

**Comment by Techcadia** [comment]
I don't feel like its worth opening a issue for this yet but @repeatedly Do you know when your going to cut the windows version?

https://td-agent-package-browser.herokuapp.com/3/windows

**Comment by Techcadia** [comment]
@repeatedly Bump

**Pull request merged**
