### PR TITLE
Extra bats tests, including configurable td-agent arguments 

### PR DESCRIPTION
**Pull request by yyuu**
1. Removed `set -e` from RedHat init script to solve #42
1. Allow configuring td-agent parameters via variables (e.g. `TD_AGENT_USER`) declared in default file
1. Fixed coding style issue in init scripts
1. Add tests and tests and tests, to avoid future regression

### CODE REVIEW

**Comment by yyuu** [comment]
@repeatedly Could you build new package with this?

@codiverse Could you check if your problem has been solved or not?

**Comment by repeatedly** [comment]
Try to build td-agent now.

**Comment by codiverse** [comment]
@repeatedly can you provide a built rpm again? If so, I'll check this for fixing #42, thanks.

**Comment by repeatedly** [comment]
@codiverse Ah, I forgot to paste the link.

https://www.dropbox.com/s/zouc0roffidyofj/td-agent-2.2.1-0.el6.x86_64.rpm?dl=0

Could you try above package?

**Comment by codiverse** [comment]
I can confirm that's fixed the init issue (#42).

**Comment by yyuu** [comment]
:smiley:

**Comment by repeatedly** [comment]
Good. We can merge this PR.

**Pull request merged**
